# Generated by Django 4.0a1 on 2021-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='display name'),
        ),
    ]
