# Generated by Django 4.0a1 on 2021-09-30 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 30, 20, 39, 25, 132422, tzinfo=utc)),
        ),
    ]
