# Generated by Django 4.0a1 on 2021-10-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
