# Generated by Django 4.0a1 on 2021-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': 'An account with this email address already exists.'}, max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(default='default-avator.jpg', upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
