# Generated by Django 4.0b1 on 2021-10-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email_alter_profile_avator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='accounts.Profile'),
        ),
    ]
