# Generated by Django 4.0a1 on 2021-10-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_bookmark_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
    ]
